name: "Patcher Action"
description: "Run Patcher commands"
author: "Gruntwork.io <grunty@gruntwork.io>"

inputs:
  github_token:
    description: "GitHub token"
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'

