name: 'Patcher'

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  patcher:
    name: 'Install Patcher'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout

      - name: Patcher
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
