name: 'Patcher Tests'

on:
  push:
    branches:
      - main

jobs:
  patcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Patcher
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          patcher_command: update
